//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/PauseControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Game.Controls
{
    public partial class @PauseControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PauseControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PauseControls"",
    ""maps"": [
        {
            ""name"": ""PauseActionMap"",
            ""id"": ""5d82a304-aef3-4cf6-a211-c8248221cf2b"",
            ""actions"": [
                {
                    ""name"": ""PauseClick"",
                    ""type"": ""Button"",
                    ""id"": ""d9b06368-0962-430f-bcae-1bf0dca96733"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89532d5c-c65d-4162-89a1-3e70388e65a3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PauseActionMap
            m_PauseActionMap = asset.FindActionMap("PauseActionMap", throwIfNotFound: true);
            m_PauseActionMap_PauseClick = m_PauseActionMap.FindAction("PauseClick", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PauseActionMap
        private readonly InputActionMap m_PauseActionMap;
        private List<IPauseActionMapActions> m_PauseActionMapActionsCallbackInterfaces = new List<IPauseActionMapActions>();
        private readonly InputAction m_PauseActionMap_PauseClick;
        public struct PauseActionMapActions
        {
            private @PauseControls m_Wrapper;
            public PauseActionMapActions(@PauseControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @PauseClick => m_Wrapper.m_PauseActionMap_PauseClick;
            public InputActionMap Get() { return m_Wrapper.m_PauseActionMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PauseActionMapActions set) { return set.Get(); }
            public void AddCallbacks(IPauseActionMapActions instance)
            {
                if (instance == null || m_Wrapper.m_PauseActionMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PauseActionMapActionsCallbackInterfaces.Add(instance);
                @PauseClick.started += instance.OnPauseClick;
                @PauseClick.performed += instance.OnPauseClick;
                @PauseClick.canceled += instance.OnPauseClick;
            }

            private void UnregisterCallbacks(IPauseActionMapActions instance)
            {
                @PauseClick.started -= instance.OnPauseClick;
                @PauseClick.performed -= instance.OnPauseClick;
                @PauseClick.canceled -= instance.OnPauseClick;
            }

            public void RemoveCallbacks(IPauseActionMapActions instance)
            {
                if (m_Wrapper.m_PauseActionMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPauseActionMapActions instance)
            {
                foreach (var item in m_Wrapper.m_PauseActionMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PauseActionMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PauseActionMapActions @PauseActionMap => new PauseActionMapActions(this);
        public interface IPauseActionMapActions
        {
            void OnPauseClick(InputAction.CallbackContext context);
        }
    }
}
